services:
  db:
    build:
      context: requirements/postgres
      dockerfile: Dockerfile
    networks:
      - transcendence
    volumes:
      - ./data/db:/var/lib/postgres/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - "5432"
    restart: unless-stopped


  web:
    networks:
      - transcendence
    build:
      context: requirements/app
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./requirements/app:/code
    expose:
      - "8000"
    environment:
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=postgres
      - SQL_USER=postgres
      - SQL_PASSWORD=postgres
      - SQL_HOST=db
      - SQL_PORT=5432
    depends_on:
      - db
    env_file:
      - .env.dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://web:8000"]
      interval: 30s
      retries: 3

  nginx:
    container_name: nginx
    networks:
      - transcendence
    depends_on:
      - web
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: .env.dev
    volumes:
      - .:/code
    ports:
      - "443:443"
      - "80:80"
    restart: on-failure

networks:
  transcendence:
    driver: bridge

