services:
  db:
    build:
      context: requirements/postgres
      dockerfile: Dockerfile
    networks:
      - transcendence
    volumes:
      - ./data/db:/var/lib/postgres/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - "3306"
    restart: unless-stopped


  web:
    networks:
      - transcendence
    build:
      context: requirements/app
    volumes:
      - .:/code
    expose:
      - "8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db

  nginx:
    container_name: nginx
    networks:
      - transcendence
    depends_on:
      - web
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - .:/code
    ports:
      - "443:443"
    restart: on-failure

networks:
  transcendence:
    driver: bridge