services:
  db:
    build:
      context: services/postgres
      dockerfile: build/Dockerfile.${DOCKERFILE_EXT}
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
    volumes:
      - postgres-db:/var/lib/postgresql/data
    expose:
      - "5432"
    networks:
      - django_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  django:
    build:
      context: ./services/django
      dockerfile: build/Dockerfile.dev
    env_file:
      - ./services/django/.env.dev
    volumes:
      - ./services/django:/code
    expose:
      - "8000"
    networks:
      - transcendence
      - django_network
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/hello"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./services/frontend
      dockerfile: build/Dockerfile.${DOCKERFILE_EXT}
    volumes:
      - /frontend/node_modules
      - ./services/frontend/core:/frontend/
    expose:
      - "8080"
    networks:
      - transcendence
      - django_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    build:
      context: ./services/nginx
      dockerfile: build/Dockerfile.${DOCKERFILE_EXT}
    env_file:
    - ./services/nginx/.env
    volumes:
      - ./services/nginx/core/config:/etc/nginx/conf.d
      - ./services/django:/code
    ports:
      - "443:443"
      - "80:80"
    networks:
      - transcendence
    depends_on:
      django:
        condition: service_healthy
      frontend:
        condition: service_healthy
    restart: on-failure

networks:
  transcendence:
    driver: bridge
  django_network:
    driver: bridge

volumes:
  postgres-db: