# Generated by Django 5.1.1 on 2024-10-24 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_userprofile_bio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['created'], 'verbose_name': 'Profile'},
        ),
    ]
