# Generated by Django 5.1.1 on 2024-10-30 19:22

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_userfriendship'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=profiles.models.upload_to),
        ),
    ]
