# Generated by Django 5.1.1 on 2024-10-31 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_userfriendship_user1_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='image_url',
        ),
    ]
