# Generated by Django 5.1.1 on 2024-11-02 02:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('wins', models.PositiveIntegerField(default=0)),
                ('losses', models.PositiveIntegerField(default=0)),
                ('perfect_games', models.PositiveIntegerField(default=0)),
                ('last_played', models.DateTimeField(blank=True, null=True)),
                ('UID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Game Stat',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PlayedGames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('username_player1', models.CharField(blank=True, max_length=256, null=True)),
                ('username_player2', models.CharField(blank=True, max_length=256, null=True)),
                ('score_player1', models.PositiveIntegerField(default=0)),
                ('score_player2', models.PositiveIntegerField(default=0)),
                ('player1_UID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player1_games', to=settings.AUTH_USER_MODEL)),
                ('player2_UID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player2_games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Game played',
                'verbose_name_plural': 'Games Played',
                'ordering': ['created'],
                'indexes': [models.Index(fields=['player1_UID', 'player2_UID'], name='game_played_player1_e12a08_idx')],
            },
        ),
    ]
