# Generated by Django 5.1.1 on 2024-10-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestats',
            name='last_played',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamestats',
            name='losses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gamestats',
            name='total_games',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gamestats',
            name='win_percentage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gamestats',
            name='wins',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
