# Generated by Django 5.1.1 on 2024-10-23 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_gamestats_last_played_alter_gamestats_losses_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamestats',
            options={'ordering': ['wins']},
        ),
    ]
