# Generated by Django 5.1.1 on 2024-10-23 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_gamestats_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamestats',
            name='win_percentage',
        ),
    ]
