# Generated by Django 5.1.1 on 2024-10-23 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_remove_gamestats_win_percentage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamestats',
            options={},
        ),
        migrations.RemoveField(
            model_name='gamestats',
            name='total_games',
        ),
    ]
