# Generated by Django 5.1.1 on 2024-10-24 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_gamestats_options_remove_gamestats_total_games'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestats',
            name='win_percentage',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
