# Generated by Django 5.1.1 on 2024-10-24 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_gamestats_win_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamestats',
            name='win_percentage',
        ),
    ]
