# Generated by Django 5.1.1 on 2024-10-24 19:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_playedgames'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamestats',
            options={'verbose_name': 'Game Stat'},
        ),
        migrations.AlterModelOptions(
            name='playedgames',
            options={'verbose_name': 'Game played'},
        ),
        migrations.AlterField(
            model_name='playedgames',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
