# Generated by Django 5.1.1 on 2024-10-24 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_alter_gamestats_options_alter_playedgames_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playedgames',
            options={'verbose_name': 'Game played', 'verbose_name_plural': 'Games Played'},
        ),
    ]
