# Generated by Django 5.1.1 on 2024-10-30 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_alter_playedgames_player1_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestats',
            name='perfect_games',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
