# Generated by Django 5.1.1 on 2024-10-30 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_gamestats_perfect_games'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamestats',
            options={'ordering': ['id'], 'verbose_name': 'Game Stat'},
        ),
        migrations.AlterModelOptions(
            name='playedgames',
            options={'ordering': ['created'], 'verbose_name': 'Game played', 'verbose_name_plural': 'Games Played'},
        ),
    ]
