# Generated by Django 5.1.1 on 2024-10-31 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_alter_gamestats_options_alter_playedgames_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='playedgames',
            name='username_player1',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
