# Generated by Django 5.1.1 on 2024-11-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_playedgames_username_player1'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestats',
            name='rank',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
