# Generated by Django 5.1.1 on 2024-11-01 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_gamestats_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamestats',
            name='rank',
        ),
    ]
