# Generated by Django 5.1.1 on 2024-10-29 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['created'], 'verbose_name': 'User'},
        ),
    ]
