# Generated by Django 5.1.1 on 2024-10-24 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_last_login'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['created'], 'verbose_name': 'User'},
        ),
    ]
